apiVersion: v1

kind: Pod

metadata:

  name: static-web

spec:

  initContainers:

    # an init containers that create directory

    - name: init-create-dir

      image: alpine

      command: ['sh', '-c', 'sleep 5 && echo "creating dir" && mkdir -p opt/log']

      volumeMounts:

        - name: data

          mountPath: /opt

  containers:

    # an app

    - name: app

      image: alpine

      command: ['sh', '-c', 'echo "app is running" && sleep infinity']

      volumeMounts:

        - name: data

          mountPath: /opt

  volumes:

    - name: data

      emptyDir: {}
